from postgres_to_hsqldb import convert_bundle
from ddl_loader import DDLBundle


def test_strips_create_schema():
    b = DDLBundle(schema_sql="CREATE SCHEMA IF NOT EXISTS public;\n",
                  tables_sql="CREATE TABLE public.x (id int);",
                  indexes_sql="", constraints_sql="")
    out = convert_bundle(b)
    assert "CREATE SCHEMA" not in out
    assert "public.x" not in out
    assert "CREATE TABLE x" in out


def test_type_substitutions():
    b = DDLBundle(schema_sql="", indexes_sql="", constraints_sql="",
                  tables_sql="CREATE TABLE t (a SERIAL, b TEXT, c NUMERIC(10,2), d TIMESTAMP WITH TIME ZONE);")
    out = convert_bundle(b)
    assert "INTEGER GENERATED BY DEFAULT AS IDENTITY" in out
    assert "LONGVARCHAR" in out
    assert "DECIMAL(10,2)" in out
    assert "TIMESTAMP" in out and "WITH TIME ZONE" not in out


def test_jsonb_downgrade_with_warning():
    b = DDLBundle(schema_sql="", indexes_sql="", constraints_sql="",
                  tables_sql="CREATE TABLE t (payload JSONB);")
    out = convert_bundle(b)
    assert "LONGVARCHAR" in out
    assert "JSONB" not in out


def test_strips_gen_random_uuid_default():
    b = DDLBundle(schema_sql="", indexes_sql="", constraints_sql="",
                  tables_sql="CREATE TABLE t (id VARCHAR(36) DEFAULT gen_random_uuid());")
    out = convert_bundle(b)
    assert "gen_random_uuid" not in out


def test_preserves_fk_and_index_sections():
    b = DDLBundle(
        schema_sql="CREATE SCHEMA IF NOT EXISTS public;",
        tables_sql="CREATE TABLE public.a (id INT PRIMARY KEY);",
        indexes_sql="CREATE INDEX ix_a_id ON public.a (id);",
        constraints_sql="ALTER TABLE public.a ADD CONSTRAINT chk_a CHECK (id > 0);",
    )
    out = convert_bundle(b)
    assert "CREATE INDEX ix_a_id ON a" in out
    assert "ALTER TABLE a" in out
    assert "CHECK (id > 0)" in out
