import re
from ddl_loader import DDLBundle


_SCHEMA_LINE = re.compile(r"(?im)^\s*CREATE\s+SCHEMA\s+[^;]+;\s*$")
_SCHEMA_QUALIFIER = re.compile(r"\bpublic\.")


_TYPE_REWRITES = [
    (re.compile(r"\bBIGSERIAL\b", re.I),                       "BIGINT GENERATED BY DEFAULT AS IDENTITY"),
    (re.compile(r"\bSERIAL\b",    re.I),                       "INTEGER GENERATED BY DEFAULT AS IDENTITY"),
    (re.compile(r"\bTIMESTAMP\s+WITH\s+TIME\s+ZONE\b", re.I),  "TIMESTAMP"),
    (re.compile(r"\bTIMESTAMPTZ\b", re.I),                     "TIMESTAMP"),
    (re.compile(r"\bNUMERIC\b", re.I),                         "DECIMAL"),
    (re.compile(r"\bJSONB\b", re.I),                           "LONGVARCHAR"),
    (re.compile(r"\bTEXT\b", re.I),                            "LONGVARCHAR"),
]

_DEFAULT_UUID = re.compile(r"\s*DEFAULT\s+gen_random_uuid\(\)", re.I)


def _strip_schema(sql: str) -> str:
    sql = _SCHEMA_LINE.sub("", sql)
    return _SCHEMA_QUALIFIER.sub("", sql)


def _rewrite_types(sql: str) -> str:
    for pat, repl in _TYPE_REWRITES:
        sql = pat.sub(repl, sql)
    sql = _DEFAULT_UUID.sub("", sql)
    return sql


def _section(title: str, body: str) -> str:
    body = body.strip()
    if not body:
        return ""
    return f"-- {title}\n{body}\n"


def convert_bundle(bundle: DDLBundle) -> str:
    parts = []
    parts.append("-- Generated from db/migrations/V001~V004 (postgres -> hsqldb)\n")
    for title, raw in [
        ("V002 tables",      bundle.tables_sql),
        ("V003 indexes",     bundle.indexes_sql),
        ("V004 constraints", bundle.constraints_sql),
    ]:
        converted = _rewrite_types(_strip_schema(raw))
        parts.append(_section(title, converted))
    return "\n".join(p for p in parts if p)


def convert_seed_files(seed_files: list) -> str:
    chunks = ["-- Generated from db/seed/* (postgres -> hsqldb)\n"]
    for p in seed_files:
        chunks.append(f"-- {p.name}\n")
        chunks.append(_rewrite_types(_strip_schema(p.read_text(encoding='utf-8'))).strip() + "\n")
    return "\n".join(chunks)
